/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author crysi
 */
public class CalculatorGUI extends javax.swing.JFrame {

    /**
     * Creates new form CalculatorGUI
     */
    public CalculatorGUI() {
        initComponents();
    }
    double answer = 0;
    List<String> signs = new ArrayList();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField = new javax.swing.JTextField();
        jButtonEight = new javax.swing.JButton();
        jButtonSeven = new javax.swing.JButton();
        jButtonNine = new javax.swing.JButton();
        jButtonTwo = new javax.swing.JButton();
        jButtonOne = new javax.swing.JButton();
        jButtonThree = new javax.swing.JButton();
        jButtonFive = new javax.swing.JButton();
        jButtonFour = new javax.swing.JButton();
        jButtonSix = new javax.swing.JButton();
        jButtonZero = new javax.swing.JButton();
        jButtonPoint = new javax.swing.JButton();
        jButtonAns = new javax.swing.JButton();
        jButtonEquals = new javax.swing.JButton();
        jButtonPlus = new javax.swing.JButton();
        jButtonMinus = new javax.swing.JButton();
        jButtonDivide = new javax.swing.JButton();
        jButtonMulti = new javax.swing.JButton();
        jButtonDel = new javax.swing.JButton();
        jButtonOff = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jTextField.setEditable(false);
        jTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        jTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldKeyPressed(evt);
            }
        });

        jButtonEight.setFont(new java.awt.Font("Proxy 9", 1, 36)); // NOI18N
        jButtonEight.setText("8");
        jButtonEight.setPreferredSize(new java.awt.Dimension(63, 63));
        jButtonEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEightActionPerformed(evt);
            }
        });

        jButtonSeven.setFont(new java.awt.Font("Proxy 9", 1, 36)); // NOI18N
        jButtonSeven.setText("7");
        jButtonSeven.setPreferredSize(new java.awt.Dimension(63, 63));
        jButtonSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSevenActionPerformed(evt);
            }
        });

        jButtonNine.setFont(new java.awt.Font("Proxy 9", 1, 36)); // NOI18N
        jButtonNine.setText("9");
        jButtonNine.setPreferredSize(new java.awt.Dimension(63, 63));
        jButtonNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNineActionPerformed(evt);
            }
        });

        jButtonTwo.setFont(new java.awt.Font("Proxy 9", 1, 36)); // NOI18N
        jButtonTwo.setText("2");
        jButtonTwo.setPreferredSize(new java.awt.Dimension(63, 63));
        jButtonTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTwoActionPerformed(evt);
            }
        });

        jButtonOne.setFont(new java.awt.Font("Proxy 9", 1, 36)); // NOI18N
        jButtonOne.setText("1");
        jButtonOne.setPreferredSize(new java.awt.Dimension(63, 63));
        jButtonOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOneActionPerformed(evt);
            }
        });

        jButtonThree.setFont(new java.awt.Font("Proxy 9", 1, 36)); // NOI18N
        jButtonThree.setText("3");
        jButtonThree.setPreferredSize(new java.awt.Dimension(63, 63));
        jButtonThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThreeActionPerformed(evt);
            }
        });

        jButtonFive.setFont(new java.awt.Font("Proxy 9", 1, 36)); // NOI18N
        jButtonFive.setText("5");
        jButtonFive.setPreferredSize(new java.awt.Dimension(63, 63));
        jButtonFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFiveActionPerformed(evt);
            }
        });

        jButtonFour.setFont(new java.awt.Font("Proxy 9", 1, 36)); // NOI18N
        jButtonFour.setText("4");
        jButtonFour.setPreferredSize(new java.awt.Dimension(63, 63));
        jButtonFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFourActionPerformed(evt);
            }
        });

        jButtonSix.setFont(new java.awt.Font("Proxy 9", 1, 36)); // NOI18N
        jButtonSix.setText("6");
        jButtonSix.setPreferredSize(new java.awt.Dimension(63, 63));
        jButtonSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSixActionPerformed(evt);
            }
        });

        jButtonZero.setFont(new java.awt.Font("Proxy 9", 1, 36)); // NOI18N
        jButtonZero.setText("0");
        jButtonZero.setPreferredSize(new java.awt.Dimension(63, 60));
        jButtonZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZeroActionPerformed(evt);
            }
        });

        jButtonPoint.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonPoint.setText(".");
        jButtonPoint.setPreferredSize(new java.awt.Dimension(63, 63));
        jButtonPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPointActionPerformed(evt);
            }
        });

        jButtonAns.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonAns.setText("A");
        jButtonAns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnsActionPerformed(evt);
            }
        });

        jButtonEquals.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jButtonEquals.setText("=");
        jButtonEquals.setPreferredSize(new java.awt.Dimension(63, 64));
        jButtonEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEqualsActionPerformed(evt);
            }
        });

        jButtonPlus.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jButtonPlus.setText("+");
        jButtonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlusActionPerformed(evt);
            }
        });

        jButtonMinus.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jButtonMinus.setText("-");
        jButtonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinusActionPerformed(evt);
            }
        });

        jButtonDivide.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jButtonDivide.setText("/");
        jButtonDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDivideActionPerformed(evt);
            }
        });

        jButtonMulti.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jButtonMulti.setText("*");
        jButtonMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultiActionPerformed(evt);
            }
        });

        jButtonDel.setFont(new java.awt.Font("RomanD", 1, 16)); // NOI18N
        jButtonDel.setText("Del");
        jButtonDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDelActionPerformed(evt);
            }
        });

        jButtonOff.setFont(new java.awt.Font("Proxy 1", 1, 24)); // NOI18N
        jButtonOff.setText("AC");
        jButtonOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOffActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jButtonZero, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jButtonPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEquals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jButtonAns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEight, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonNine, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonOff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTextField)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonFour, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonTwo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonFive, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSix, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonThree, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonPlus, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                            .addComponent(jButtonDivide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonMinus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonMulti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonDel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonOff, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(jButtonNine, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(jButtonEight, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(jButtonSeven, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonSix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDivide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMulti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonFive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonFour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonMinus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPlus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonThree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonTwo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEquals, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                    .addComponent(jButtonPoint, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonZero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZeroActionPerformed
        // TODO add your handling code here:
        jTextField.setText(jTextField.getText() + "0");
        if (!jTextField.hasFocus()) {
          jTextField.requestFocus();  
        }
    }//GEN-LAST:event_jButtonZeroActionPerformed

    private void jButtonOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOneActionPerformed
        // TODO add your handling code here:
        jTextField.setText(jTextField.getText() + "1");
        if (!jTextField.hasFocus()) {
          jTextField.requestFocus();  
        }
    }//GEN-LAST:event_jButtonOneActionPerformed

    private void jButtonTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTwoActionPerformed
        // TODO add your handling code here:
        jTextField.setText(jTextField.getText() + "2");
        if (!jTextField.hasFocus()) {
          jTextField.requestFocus();  
        }
    }//GEN-LAST:event_jButtonTwoActionPerformed

    private void jButtonThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThreeActionPerformed
        // TODO add your handling code here:
        jTextField.setText(jTextField.getText() + "3");
        if (!jTextField.hasFocus()) {
          jTextField.requestFocus();  
        }
    }//GEN-LAST:event_jButtonThreeActionPerformed

    private void jButtonFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFourActionPerformed
        // TODO add your handling code here:
        jTextField.setText(jTextField.getText() + "4");
        if (!jTextField.hasFocus()) {
          jTextField.requestFocus();  
        }
    }//GEN-LAST:event_jButtonFourActionPerformed

    private void jButtonFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFiveActionPerformed
        // TODO add your handling code here:
        jTextField.setText(jTextField.getText() + "5");
        if (!jTextField.hasFocus()) {
          jTextField.requestFocus();  
        }
    }//GEN-LAST:event_jButtonFiveActionPerformed

    private void jButtonSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSixActionPerformed
        // TODO add your handling code here:
        jTextField.setText(jTextField.getText() + "6");
        if (!jTextField.hasFocus()) {
          jTextField.requestFocus();  
        }
    }//GEN-LAST:event_jButtonSixActionPerformed

    private void jButtonSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSevenActionPerformed
        // TODO add your handling code here:
        jTextField.setText(jTextField.getText() + "7");
        if (!jTextField.hasFocus()) {
          jTextField.requestFocus();  
        }
    }//GEN-LAST:event_jButtonSevenActionPerformed

    private void jButtonEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEightActionPerformed
        // TODO add your handling code here:
        jTextField.setText(jTextField.getText() + "8");
        if (!jTextField.hasFocus()) {
          jTextField.requestFocus();  
        }
    }//GEN-LAST:event_jButtonEightActionPerformed

    private void jButtonNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNineActionPerformed
        // TODO add your handling code here:
        jTextField.setText(jTextField.getText() + "9");
        if (!jTextField.hasFocus()) {
          jTextField.requestFocus();  
        }
    }//GEN-LAST:event_jButtonNineActionPerformed

    private void jButtonPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPointActionPerformed
        // TODO add your handling code here:
        jTextField.setText(jTextField.getText() + ".");
        if (!jTextField.hasFocus()) {
          jTextField.requestFocus();  
        }
    }//GEN-LAST:event_jButtonPointActionPerformed

    private void jButtonAnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnsActionPerformed
        // TODO add your handling code here:
        jTextField.setText(jTextField.getText() + answer);
        if (!jTextField.hasFocus()) {
          jTextField.requestFocus();  
        }
    }//GEN-LAST:event_jButtonAnsActionPerformed

    private void jButtonMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultiActionPerformed
        // TODO add your handling code here:
        jTextField.setText(jTextField.getText() + " * ");
        String multi = "*";
        signs.add(multi);
        if (!jTextField.hasFocus()) {
          jTextField.requestFocus();  
        }
    }//GEN-LAST:event_jButtonMultiActionPerformed

    private void jButtonDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivideActionPerformed
        // TODO add your handling code here:
        jTextField.setText(jTextField.getText() + " / ");
        String divide = "/";
        signs.add(divide);
        if (!jTextField.hasFocus()) {
          jTextField.requestFocus();  
        }
    }//GEN-LAST:event_jButtonDivideActionPerformed

    private void jButtonPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlusActionPerformed
        // TODO add your handling code here:
        jTextField.setText(jTextField.getText() + " + ");
        String plus = "+";
        signs.add(plus);
        if (!jTextField.hasFocus()) {
          jTextField.requestFocus();  
        }
    }//GEN-LAST:event_jButtonPlusActionPerformed

    private void jButtonMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinusActionPerformed
        // TODO add your handling code here:
        jTextField.setText(jTextField.getText() + " - ");
        String minus = "-";
        signs.add(minus);
        if (!jTextField.hasFocus()) {
          jTextField.requestFocus();  
        }
    }//GEN-LAST:event_jButtonMinusActionPerformed

    @SuppressWarnings("SleepWhileInLoop")
    private void jButtonEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEqualsActionPerformed
        String numberText = jTextField.getText();
        numberText = numberText.replace("+", ":");
        numberText = numberText.replace("-", ":");
        numberText = numberText.replace("*", ":");
        numberText = numberText.replace("/", ":");
        numberText = numberText.replace(" ", "");
        String[] orginalNumberText = numberText.split(":");
        
        List<String> test = new ArrayList<>();

        int num = 0;
        int position;
        double numberParsed1;
        double numberParsed2;
        while (num != orginalNumberText.length) {
            test.add(num, orginalNumberText[num]);
            num++;
        }
        while (signs.contains("/")) {
            position = signs.indexOf("/");
            numberParsed1 = Double.parseDouble(test.get(position));
            position++;
            numberParsed2 = Double.parseDouble(test.get(position));
            test.remove(test.get(position));
            test.remove(test.get(position - 1));
            answer = numberParsed1 / numberParsed2;
            jTextField.setText("" + answer);
            String answerString = jTextField.getText();
            signs.remove("/");
            position--;
            test.add(position, answerString);
        }
        while (signs.contains("*")) {
            position = signs.indexOf("*");
            numberParsed1 = Double.parseDouble(test.get(position));
            position++;
            numberParsed2 = Double.parseDouble(test.get(position));
            test.remove(test.get(position));
            test.remove(test.get(position - 1));
            answer = numberParsed1 * numberParsed2;
            jTextField.setText("" + answer);
            String answerString = jTextField.getText();
            signs.remove("*");
            position--;
            test.add(position, answerString);
        }
        while (signs.contains("-")) {
            position = signs.indexOf("-");
            numberParsed1 = Double.parseDouble(test.get(position));
            position++;
            numberParsed2 = Double.parseDouble(test.get(position));
            test.remove(test.get(position));
            test.remove(test.get(position - 1));
            answer = numberParsed1 - numberParsed2;
            jTextField.setText("" + answer);
            String answerString = jTextField.getText();
            signs.remove("-");
            position--;
            test.add(position, answerString);
        }
        while (signs.contains("+")) {
            position = signs.indexOf("+");
            numberParsed1 = Double.parseDouble(test.get(position));
            position++;
            numberParsed2 = Double.parseDouble(test.get(position));
            test.remove(test.get(position));
            test.remove(test.get(position - 1));
            answer = numberParsed1 + numberParsed2;
            jTextField.setText("" + answer);
            String answerString = jTextField.getText();
            signs.remove("+");
            position--;
            test.add(position, answerString);
        }
        if (!jTextField.hasFocus()) {
          jTextField.requestFocus();  
        }
    }//GEN-LAST:event_jButtonEqualsActionPerformed

    private void jButtonDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDelActionPerformed
        // TODO add your handling code here:
        if (!jTextField.hasFocus()) {
          jTextField.requestFocus();  
        }
        jTextField.setText(jTextField.getText() + ";");
        char[] items = jTextField.getText().toCharArray();
        int characterDelete = items.length - 2;
        String item = String.valueOf(items[characterDelete]);
        String replacement = jTextField.getText().replace(item + ";", "");
        if (items[characterDelete] == '*') {
            String multi = "*";
            signs.remove(multi);
        }
        if (items[characterDelete] == '/') {
            String divide = "/";
            signs.remove(divide);
        }
        if (items[characterDelete] == '-') {
            String minus = "-";
            signs.remove(minus);
        }
        if (items[characterDelete] == '+') {
            String plus = "+";
            signs.remove(plus);
        }
        jTextField.setText(replacement);
    }//GEN-LAST:event_jButtonDelActionPerformed

    private void jButtonOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOffActionPerformed
        // TODO add your handling code here
        if (!jTextField.hasFocus()) {
          jTextField.requestFocus();  
        }
        signs.clear();
        jTextField.setText("");
        System.gc();
    }//GEN-LAST:event_jButtonOffActionPerformed

    private void jTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldKeyPressed

        if (evt.getKeyChar() == '0' || evt.getKeyCode() == 155) {
            jTextField.setText(jTextField.getText() + "0");
        }
        if (evt.getKeyChar() == '1' || evt.getKeyCode() == 35) {
            jTextField.setText(jTextField.getText() + "1");
        }
        if (evt.getKeyChar() == '2' || evt.getKeyCode() == 40) {
            jTextField.setText(jTextField.getText() + "2");
        }
        if (evt.getKeyChar() == '3' || evt.getKeyCode() == 34) {
            jTextField.setText(jTextField.getText() + "3");
        }
        if (evt.getKeyChar() == '4' || evt.getKeyCode() == 37) {
            jTextField.setText(jTextField.getText() + "4");
        }
        if (evt.getKeyChar() == '5' || evt.getKeyCode() == 12) {
            jTextField.setText(jTextField.getText() + "5");
        }
        if (evt.getKeyChar() == '6' || evt.getKeyCode() == 39) {
            jTextField.setText(jTextField.getText() + "6");
        }
        if (evt.getKeyChar() == '7' || evt.getKeyCode() == 36) {
            jTextField.setText(jTextField.getText() + "7");
        }
        if (evt.getKeyChar() == '8' || evt.getKeyCode() == 38) {
            jTextField.setText(jTextField.getText() + "8");
        }
        if (evt.getKeyChar() == '9' || evt.getKeyCode() == 33) {
            jTextField.setText(jTextField.getText() + "9");
        }
        if (evt.getKeyChar() == '.') {
            jTextField.setText(jTextField.getText() + ".");
        }
        if (evt.getKeyCode() == 10) {
            jButtonEquals.doClick();
        }
        if (evt.getKeyCode() == 127) {
            jButtonDel.doClick();
        }
        if (evt.getKeyChar() == '+') {
            jButtonPlus.doClick();
        }
        if (evt.getKeyChar() == '/') {
            jButtonDivide.doClick();
        }
        if (evt.getKeyChar() == '*') {
            jButtonMulti.doClick();
        }
        if (evt.getKeyChar() == '-') {
            jButtonMinus.doClick();
        }
    }//GEN-LAST:event_jTextFieldKeyPressed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        if (!jTextField.hasFocus()) {
          jTextField.requestFocus();  
        }
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("System".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CalculatorGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAns;
    private javax.swing.JButton jButtonDel;
    private javax.swing.JButton jButtonDivide;
    private javax.swing.JButton jButtonEight;
    private javax.swing.JButton jButtonEquals;
    private javax.swing.JButton jButtonFive;
    private javax.swing.JButton jButtonFour;
    private javax.swing.JButton jButtonMinus;
    private javax.swing.JButton jButtonMulti;
    private javax.swing.JButton jButtonNine;
    private javax.swing.JButton jButtonOff;
    private javax.swing.JButton jButtonOne;
    private javax.swing.JButton jButtonPlus;
    private javax.swing.JButton jButtonPoint;
    private javax.swing.JButton jButtonSeven;
    private javax.swing.JButton jButtonSix;
    private javax.swing.JButton jButtonThree;
    private javax.swing.JButton jButtonTwo;
    private javax.swing.JButton jButtonZero;
    private javax.swing.JTextField jTextField;
    // End of variables declaration//GEN-END:variables
}
